// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagementSystem.Data;

#nullable disable

namespace TaskManagementSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250122184621_22 JAN")]
    partial class _22JAN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e15ce2eb-3781-4351-a205-dc133f889d57",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "335f4107-9914-4d65-9542-92db92194c0b",
                            Name = "TaskManager",
                            NormalizedName = "TASKMANAGER"
                        },
                        new
                        {
                            Id = "29d8720e-11e4-466c-9b6f-ced906a1cf47",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "384df32d-2a7c-4147-baf1-152db746565b",
                            RoleId = "e15ce2eb-3781-4351-a205-dc133f889d57"
                        },
                        new
                        {
                            UserId = "16914ec6-4686-4c2c-ba58-5a9c3c15f404",
                            RoleId = "335f4107-9914-4d65-9542-92db92194c0b"
                        },
                        new
                        {
                            UserId = "4c5d1a8e-4f28-4ed5-8427-b72f0df86619",
                            RoleId = "29d8720e-11e4-466c-9b6f-ced906a1cf47"
                        },
                        new
                        {
                            UserId = "68ed7806-e19b-4610-8146-e999b0732379",
                            RoleId = "29d8720e-11e4-466c-9b6f-ced906a1cf47"
                        },
                        new
                        {
                            UserId = "4d7b0c08-5565-420b-854e-10e8b3ea69d6",
                            RoleId = "29d8720e-11e4-466c-9b6f-ced906a1cf47"
                        },
                        new
                        {
                            UserId = "06827f01-662b-4641-abce-b1c496f28660",
                            RoleId = "29d8720e-11e4-466c-9b6f-ced906a1cf47"
                        },
                        new
                        {
                            UserId = "fd65ce29-7600-446a-a89f-f3422bead07e",
                            RoleId = "29d8720e-11e4-466c-9b6f-ced906a1cf47"
                        },
                        new
                        {
                            UserId = "37bded91-485a-44b5-bbc7-53e5be7c3d0b",
                            RoleId = "29d8720e-11e4-466c-9b6f-ced906a1cf47"
                        },
                        new
                        {
                            UserId = "873d2b23-002a-477f-856e-5ed602b5405c",
                            RoleId = "29d8720e-11e4-466c-9b6f-ced906a1cf47"
                        },
                        new
                        {
                            UserId = "336722d0-5991-49a5-ab55-d7414b598c63",
                            RoleId = "29d8720e-11e4-466c-9b6f-ced906a1cf47"
                        },
                        new
                        {
                            UserId = "d15c6625-2ded-49e4-b8b9-1f1738a696e3",
                            RoleId = "29d8720e-11e4-466c-9b6f-ced906a1cf47"
                        },
                        new
                        {
                            UserId = "102075be-a710-4035-87e0-25f7295074e6",
                            RoleId = "29d8720e-11e4-466c-9b6f-ced906a1cf47"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "384df32d-2a7c-4147-baf1-152db746565b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e926a58a-ad5b-4593-b90d-cd85b179507d",
                            DateOfBirth = new DateOnly(2024, 11, 15),
                            DepartmentName = "IT Support",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "admin",
                            LastName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDIJhlOB8V74U3Ob4FQcTWv9ydLBR90IBThG2BkJ9of0EW6M+y97yhwrnUcw0Tka0A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e80c1932-f0bd-413b-8a60-9eb483440d05",
                            SkillLevel = 10,
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "16914ec6-4686-4c2c-ba58-5a9c3c15f404",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "82a89260-1890-4a03-bd45-4267c1af18c9",
                            DateOfBirth = new DateOnly(2024, 11, 15),
                            DepartmentName = "IT Support",
                            Email = "taskManager@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "taskManager",
                            LastName = "taskManager",
                            LockoutEnabled = false,
                            NormalizedEmail = "TASKMANAGER@LOCALHOST.COM",
                            NormalizedUserName = "TASKMANAGER@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPdYnKCFOOpoXc7clOt6SsHpKETBTIRgyubzzeJvZ1qu7nr1EHBsK7dxzhNcAskJlQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "39db5faa-83f8-4a10-993a-4da595f5ee72",
                            SkillLevel = 10,
                            TwoFactorEnabled = false,
                            UserName = "taskManager@localhost.com"
                        },
                        new
                        {
                            Id = "4c5d1a8e-4f28-4ed5-8427-b72f0df86619",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "339c99c7-4e1c-4f0e-ad6a-ec382c25c696",
                            DateOfBirth = new DateOnly(1998, 11, 20),
                            DepartmentName = "IT Support",
                            Email = "empl1@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "empl1",
                            LastName = "empl1",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPL1@LOCALHOST.COM",
                            NormalizedUserName = "EMPL1@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBr4YXyiKfBvGpaKRh49UWwFn1NQR5SFS60p0BsXK3S5Nwem968Nhtq3fHrSse/uzg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "131c88ee-a630-4590-8119-66a99c445abe",
                            SkillLevel = 7,
                            TwoFactorEnabled = false,
                            UserName = "empl1@localhost.com"
                        },
                        new
                        {
                            Id = "68ed7806-e19b-4610-8146-e999b0732379",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7ee2596d-3b7e-4686-aa8c-d5281e845ea9",
                            DateOfBirth = new DateOnly(1990, 11, 15),
                            DepartmentName = "IT Support",
                            Email = "empl2@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "empl2",
                            LastName = "empl2",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPL2@LOCALHOST.COM",
                            NormalizedUserName = "EMPL2@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHwUGQrNNJtWCHl71mPqHXpfDfFZJofWkqDaBFlG20v4e43qCXSu0+P2a16SqZauEQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "52497999-1fdf-4ee0-abae-913c1380d9bc",
                            SkillLevel = 9,
                            TwoFactorEnabled = false,
                            UserName = "empl2@localhost.com"
                        },
                        new
                        {
                            Id = "4d7b0c08-5565-420b-854e-10e8b3ea69d6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab62af45-ab42-4d69-ac58-3ed1e0a6378b",
                            DateOfBirth = new DateOnly(1995, 1, 15),
                            DepartmentName = "IT Support",
                            Email = "empl3@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "empl3",
                            LastName = "empl3",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPL3@LOCALHOST.COM",
                            NormalizedUserName = "EMPL3@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBmYLPKLqoLnqXjzhaAbey0e+4PilbqKjfa+/A9nQuZH3G7j6m2jAtjZ+IyCAnU2kA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ccda6b5e-5bb9-4ed9-b489-fc93d1c3250a",
                            SkillLevel = 6,
                            TwoFactorEnabled = false,
                            UserName = "empl3@localhost.com"
                        },
                        new
                        {
                            Id = "06827f01-662b-4641-abce-b1c496f28660",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d57c2d8-243c-4b34-946f-8b3f11119fb1",
                            DateOfBirth = new DateOnly(1999, 11, 15),
                            DepartmentName = "Development",
                            Email = "empl4@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "empl4",
                            LastName = "empl4",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPL4@LOCALHOST.COM",
                            NormalizedUserName = "EMPL4@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELeMm4cLDZAunzLUNDMoGPfx2tvjGZnwGkk7vEaVlkbU9qxtlSQBKAc2NiW6Ij7vuQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "090dd3f3-3f7d-481c-92d4-4405298479da",
                            SkillLevel = 10,
                            TwoFactorEnabled = false,
                            UserName = "empl4@localhost.com"
                        },
                        new
                        {
                            Id = "fd65ce29-7600-446a-a89f-f3422bead07e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00089ff2-3000-4f83-aae5-5f974d596144",
                            DateOfBirth = new DateOnly(2000, 11, 15),
                            DepartmentName = "Development",
                            Email = "empl5@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "empl5",
                            LastName = "empl5",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPL5@LOCALHOST.COM",
                            NormalizedUserName = "EMPL5@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEKdr5B0CZq8Waq+SM4xUdOebHgP1x34OestdwzxNcsD68MtXHJQXJSyP3RJ26aWJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "58426b81-102c-48e0-aab2-9b22261dfe84",
                            SkillLevel = 6,
                            TwoFactorEnabled = false,
                            UserName = "empl5@localhost.com"
                        },
                        new
                        {
                            Id = "37bded91-485a-44b5-bbc7-53e5be7c3d0b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2cf06f06-8b08-46a2-b85b-5144fdf404d7",
                            DateOfBirth = new DateOnly(1999, 3, 22),
                            DepartmentName = "Development",
                            Email = "empl6@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "empl6",
                            LastName = "empl6",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPL6@LOCALHOST.COM",
                            NormalizedUserName = "EMPL6@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJD24VYGZ4M8C4SYd1RFI7YGzem1B/MHYRKVlxQWgPXnfjL/4gzw7SpYXBTfffykNA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c8192b10-7cd3-4524-918a-dde0891813d1",
                            SkillLevel = 7,
                            TwoFactorEnabled = false,
                            UserName = "empl6@localhost.com"
                        },
                        new
                        {
                            Id = "873d2b23-002a-477f-856e-5ed602b5405c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7084040d-ea02-4b66-9a82-77453f113ec1",
                            DateOfBirth = new DateOnly(1980, 10, 20),
                            DepartmentName = "Development",
                            Email = "empl7@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "empl7",
                            LastName = "empl7",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPL7@LOCALHOST.COM",
                            NormalizedUserName = "EMPL7@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKCP6aedxlidPUmSi/pWkbzVKj1l7OBFPP9wggVVFCFoW8oFFuqaR6nByRWFB5ky0g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "562dd627-2124-46cf-8997-6456063b5f28",
                            SkillLevel = 7,
                            TwoFactorEnabled = false,
                            UserName = "empl7@localhost.com"
                        },
                        new
                        {
                            Id = "336722d0-5991-49a5-ab55-d7414b598c63",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d0cbff39-9a6d-4782-8fac-271dad675115",
                            DateOfBirth = new DateOnly(1997, 8, 8),
                            DepartmentName = "Marketing",
                            Email = "empl8@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "empl8",
                            LastName = "empl8",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPL8@LOCALHOST.COM",
                            NormalizedUserName = "EMPL8@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECuXYje8kJDNCck+yq0ISzQaBRX8Z8QjYCuzZ/wzrRyEdu34/PLjCMH+0ms/qSNZhw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e19b676-e9f0-4fe8-a71b-d76ee1dfba21",
                            SkillLevel = 10,
                            TwoFactorEnabled = false,
                            UserName = "empl8@localhost.com"
                        },
                        new
                        {
                            Id = "d15c6625-2ded-49e4-b8b9-1f1738a696e3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5b478208-9aff-4b7d-a540-900082ed4c9c",
                            DateOfBirth = new DateOnly(1989, 11, 15),
                            DepartmentName = "Marketing",
                            Email = "empl9@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "empl9",
                            LastName = "empl9",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPL9@LOCALHOST.COM",
                            NormalizedUserName = "EMPL9@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPqtbwd2g8V7qxje1qMsyVBXbR/+2oA7+uDR5mbjhOJpjPim+NMjw55lLOgLUsVWHA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "52c2ed78-177b-4d99-8e10-d73df061b8fe",
                            SkillLevel = 7,
                            TwoFactorEnabled = false,
                            UserName = "empl9@localhost.com"
                        },
                        new
                        {
                            Id = "102075be-a710-4035-87e0-25f7295074e6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "756b2ee2-ae6c-4669-a95b-92a58bf14f32",
                            DateOfBirth = new DateOnly(1999, 7, 22),
                            DepartmentName = "Marketing",
                            Email = "empl10@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "empl10",
                            LastName = "empl10",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPL10@LOCALHOST.COM",
                            NormalizedUserName = "EMPL10@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMW8QcJ5ZptebXzgpkjHWvLH+j/EiR64wsEKwIngqYS2yJo8Hwwe2yTX8Eewn8d/dg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b6c38951-c717-4576-a466-3e1c2a9641c7",
                            SkillLevel = 6,
                            TwoFactorEnabled = false,
                            UserName = "empl10@localhost.com"
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Data.TaskAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WorkingDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TaskTypeId")
                        .IsUnique();

                    b.HasIndex("WorkingDayId");

                    b.ToTable("TaskAllocations");
                });

            modelBuilder.Entity("TaskManagementSystem.Data.TaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Allocated")
                        .HasColumnType("bit");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("TaskTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allocated = false,
                            Completed = false,
                            Department = "Development",
                            Description = "You must complete the classes",
                            EndTime = new TimeOnly(11, 30, 0),
                            Name = "Develop the banking app",
                            SkillLevel = 10,
                            StartDate = new DateOnly(2025, 1, 31),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Allocated = false,
                            Completed = false,
                            Department = "Development",
                            Description = "Fix all reported database errors",
                            EndTime = new TimeOnly(11, 30, 0),
                            Name = "Fix database issues",
                            SkillLevel = 6,
                            StartDate = new DateOnly(2025, 1, 31),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Allocated = false,
                            Completed = false,
                            Department = "IT Support",
                            Description = "Implement additional firewalls",
                            EndTime = new TimeOnly(17, 0, 0),
                            Name = "Enhance security measures",
                            SkillLevel = 8,
                            StartDate = new DateOnly(2025, 1, 31),
                            StartTime = new TimeOnly(11, 30, 0)
                        },
                        new
                        {
                            Id = 4,
                            Allocated = false,
                            Completed = false,
                            Department = "Marketing",
                            Description = "Prepare new posters and flyers",
                            EndTime = new TimeOnly(11, 30, 0),
                            Name = "Design new campaign materials",
                            SkillLevel = 5,
                            StartDate = new DateOnly(2025, 1, 31),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Allocated = false,
                            Completed = false,
                            Department = "Development",
                            Description = "Refactor legacy code",
                            EndTime = new TimeOnly(17, 0, 0),
                            Name = "Improve code quality",
                            SkillLevel = 7,
                            StartDate = new DateOnly(2025, 1, 31),
                            StartTime = new TimeOnly(11, 30, 0)
                        },
                        new
                        {
                            Id = 6,
                            Allocated = false,
                            Completed = false,
                            Department = "Development",
                            Description = "Integrate with external APIs",
                            EndTime = new TimeOnly(17, 0, 0),
                            Name = "Implement API integration",
                            SkillLevel = 9,
                            StartDate = new DateOnly(2025, 2, 3),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            Allocated = false,
                            Completed = false,
                            Department = "IT Support",
                            Description = "Run diagnostics on the company network",
                            EndTime = new TimeOnly(17, 0, 0),
                            Name = "Network diagnostics",
                            SkillLevel = 7,
                            StartDate = new DateOnly(2025, 2, 3),
                            StartTime = new TimeOnly(11, 30, 0)
                        },
                        new
                        {
                            Id = 8,
                            Allocated = false,
                            Completed = false,
                            Department = "Marketing",
                            Description = "Plan next month’s social media campaigns",
                            EndTime = new TimeOnly(11, 30, 0),
                            Name = "Social media strategy",
                            SkillLevel = 6,
                            StartDate = new DateOnly(2025, 2, 3),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            Allocated = false,
                            Completed = false,
                            Department = "IT Support",
                            Description = "Close all pending customer tickets",
                            EndTime = new TimeOnly(11, 30, 0),
                            Name = "Resolve customer tickets",
                            SkillLevel = 5,
                            StartDate = new DateOnly(2025, 2, 3),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            Allocated = false,
                            Completed = false,
                            Department = "Development",
                            Description = "Design and code a new landing page",
                            EndTime = new TimeOnly(17, 0, 0),
                            Name = "Create landing page",
                            SkillLevel = 8,
                            StartDate = new DateOnly(2025, 2, 3),
                            StartTime = new TimeOnly(11, 30, 0)
                        },
                        new
                        {
                            Id = 11,
                            Allocated = false,
                            Completed = false,
                            Department = "Development",
                            Description = "Resolve reported bugs in production",
                            EndTime = new TimeOnly(11, 30, 0),
                            Name = "Bug fixes in existing app",
                            SkillLevel = 8,
                            StartDate = new DateOnly(2025, 2, 4),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            Allocated = false,
                            Completed = false,
                            Department = "IT Support",
                            Description = "Install new servers",
                            EndTime = new TimeOnly(17, 0, 0),
                            Name = "Upgrade system hardware",
                            SkillLevel = 10,
                            StartDate = new DateOnly(2025, 2, 4),
                            StartTime = new TimeOnly(11, 30, 0)
                        },
                        new
                        {
                            Id = 13,
                            Allocated = false,
                            Completed = false,
                            Department = "Marketing",
                            Description = "Draft and finalize press release for new product launch",
                            EndTime = new TimeOnly(17, 0, 0),
                            Name = "Prepare press release",
                            SkillLevel = 7,
                            StartDate = new DateOnly(2025, 2, 4),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            Allocated = false,
                            Completed = false,
                            Department = "Development",
                            Description = "Perform QA testing on new features",
                            EndTime = new TimeOnly(11, 30, 0),
                            Name = "Test new features",
                            SkillLevel = 6,
                            StartDate = new DateOnly(2025, 2, 4),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            Allocated = false,
                            Completed = false,
                            Department = "Marketing",
                            Description = "Optimize website for search engines",
                            EndTime = new TimeOnly(17, 0, 0),
                            Name = "SEO optimization",
                            SkillLevel = 9,
                            StartDate = new DateOnly(2025, 2, 4),
                            StartTime = new TimeOnly(11, 30, 0)
                        },
                        new
                        {
                            Id = 16,
                            Allocated = false,
                            Completed = false,
                            Department = "IT Support",
                            Description = "Create a backup of all systems",
                            EndTime = new TimeOnly(11, 30, 0),
                            Name = "Data backup",
                            SkillLevel = 6,
                            StartDate = new DateOnly(2025, 2, 4),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            Allocated = false,
                            Completed = false,
                            Department = "Development",
                            Description = "Create test cases for upcoming releases",
                            EndTime = new TimeOnly(17, 0, 0),
                            Name = "Develop test cases",
                            SkillLevel = 7,
                            StartDate = new DateOnly(2025, 2, 4),
                            StartTime = new TimeOnly(11, 30, 0)
                        },
                        new
                        {
                            Id = 18,
                            Allocated = false,
                            Completed = false,
                            Department = "Marketing",
                            Description = "Prepare and send out promotional emails",
                            EndTime = new TimeOnly(11, 30, 0),
                            Name = "Manage email campaigns",
                            SkillLevel = 5,
                            StartDate = new DateOnly(2025, 2, 4),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            Allocated = false,
                            Completed = false,
                            Department = "IT Support",
                            Description = "Deploy patches to all systems",
                            EndTime = new TimeOnly(17, 0, 0),
                            Name = "Software patch update",
                            SkillLevel = 8,
                            StartDate = new DateOnly(2025, 2, 4),
                            StartTime = new TimeOnly(11, 30, 0)
                        },
                        new
                        {
                            Id = 20,
                            Allocated = false,
                            Completed = false,
                            Department = "Marketing",
                            Description = "Prepare a presentation for clients",
                            EndTime = new TimeOnly(17, 0, 0),
                            Name = "Create client presentation",
                            SkillLevel = 7,
                            StartDate = new DateOnly(2025, 2, 4),
                            StartTime = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Data.WorkingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("WorkingDays");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TaskManagementSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TaskManagementSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagementSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TaskManagementSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManagementSystem.Data.TaskAllocation", b =>
                {
                    b.HasOne("TaskManagementSystem.Data.ApplicationUser", "Employee")
                        .WithMany("TaskAllocations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagementSystem.Data.TaskType", "TaskType")
                        .WithOne("TaskAllocation")
                        .HasForeignKey("TaskManagementSystem.Data.TaskAllocation", "TaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagementSystem.Data.WorkingDay", "WorkingDay")
                        .WithMany()
                        .HasForeignKey("WorkingDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TaskType");

                    b.Navigation("WorkingDay");
                });

            modelBuilder.Entity("TaskManagementSystem.Data.ApplicationUser", b =>
                {
                    b.Navigation("TaskAllocations");
                });

            modelBuilder.Entity("TaskManagementSystem.Data.TaskType", b =>
                {
                    b.Navigation("TaskAllocation");
                });
#pragma warning restore 612, 618
        }
    }
}
